server:
  port: 8081

spring:
  application:
    name: psi-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "root123"
    type: com.alibaba.druid.pool.DruidDataSource
    url: "jdbc:mysql://localhost:3306/primeton?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false

mybatis:
   configLocation: classpath:mybatis-config.xml
   mapperLocations: classpath:com/caih/cloudec/financial/dao/**/*.xml

